spring.application.name=adoptions
#
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
#
spring.ai.ollama.chat.model=gemma4:26b
spring.ai.ollama.embedding.model=embeddinggemma:latest
#
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
#
spring.ai.mcp.client.streamable-http.connections.scheduler.url=http://localhost:8081
